#!/bin/sh

#set -e

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

export LANG=cs_CZ.utf8
export COLUMNS=80

. /scripts/functions
. /etc/common-functions

log_begin_msg "Obnova-ng starting..."

ldconfig
ln -sf /tmp/etc/obnova-joined.conf /etc/obnova.conf
mkdir -p /dev/pts /tmp /sys /sys/
mount -a -n
mkdir -p /var/run/sshd
chown root.root /var/run/sshd
chmod 600 /var/run/sshd

reset
logolite

for i in 1 2 3 4 5 6 7 8 9; do
  mknod /dev/tty$i c 4 $i;
  /bin/setupcon >/dev/tty$i </dev/tty$i
done
mknod /dev/null c 1 3
(while true; do /bin/openvt -w -c 3 -s -f /bin/sh; sleep 1; done) >/dev/null 2>/dev/null &
(while true; do /bin/openvt -w -c 7 -s -f /bin/sh; sleep 1; done) >/dev/null 2>/dev/null &
mount -t devtmpfs devtmpfs /dev

logo

echo "*.* @@syslog" >>/etc/rsyslog.conf

/bin/openvt -c 4 -f /bin/top
(sleep 10; /bin/openvt -c 5 -f /bin/iftop ) &

if /bin/openvt -w -c 2 -s -f /bin/obnovang-stage2; then
  log_begin_msg "Obnova ended."
  sleep 600
  halt
else
  log_begin_msg "Obnova error!"
  halt
fi

log_end_msg

