#!/bin/sh
#
# This script is part of OBNOVA system by Lukas Kubin,
# http://obnova.sourceforge.net
#
# Copyright (C) 2003,2004 Lukas Kubin
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#

. /etc/obnova.conf
. /etc/common-functions

#
# Ensure the Obnova data files are
# currently not being updated
#
checkBusyGroup

ALLENTRIES=$(grep -v "^#" $COMPLIST | sed -e "s/\(.*\)\#.*/\1/" | grep -i $MAC | cut -d"," -f3-)
REG_WORKGROUP=$(echo $ALLENTRIES|cut -d"," -f1)
REG_POPIS=$(echo $ALLENTRIES|cut -d"," -f2)

#
# Do the sync for each partition available
#
echo -n "Zjistuji dostupne partitions pro obnovu ($PARTGREP)."
PARTITIONS=$(rsync $OBNOVAPATH/data/$GROUPNAME/base/|sed s'/.* \(.*\)$/\1/'|grep -v "^\."| $PARTGREP)
if [ $? -eq 0 ] && ! [ cat /proc/cmdline | grep udp >/dev/null ] ; then
	echo -e $TOK
else
	echo -e $TNOK
	echo -e "Nepodarilo se zjistit dostupne partitions"
fi

if cat /proc/cmdline | grep udpsender >/dev/null ; then
  /bin/udpcast sender `echo $PARTGREP | cut -d ' ' -f 2`
  exitfunc $?
fi

if cat /proc/cmdline | grep udpreceiver >/dev/null ; then
  /bin/udpcast receiver `echo $PARTGREP | cut -d ' ' -f 2`
  exitfunc $?
fi

if cat /proc/cmdline | grep ' compr' >/dev/null ; then
  RSYNC_PARAMS_EXTRASRESTORE="-z $RSYNC_PARAMS_EXTRASRESTORE"
  RSYNC_PARAMS_BASERESTORE="-z $RSYNC_PARAMS_BASERESTORE"
fi

for PARTITION in $PARTITIONS
do
	log 3 "starting renewal of $PARTITION"
	#
	# Mount the partition to restore
	#
	MOUNTPOINT=$TMPDIR/$PARTITION
	mountPartition /dev/$PARTITION $MOUNTPOINT

	#
	# First do "fake" extras sync to get list of files to be
	# excluded during base restore
	#
	EXTRASLIST=$TMPDIR/extraslist; rm -f $EXTRASLIST; touch $EXTRASLIST
	EXTRASLISTNEW=$TMPDIR/extraslistnew; rm -f $EXTRASLISTNEW; touch $EXTRASLISTNEW
	if [ "$DATAEXTRASFILESEXISTS" != "false" ]; then
		log 3 "looking for files to extras sync"
		rsync $RSYNC_PARAMS_EXTRASRESTORE -n $OBNOVAPATH/data/$GROUPNAME/extras/$MAC/$PARTITION/ 2>/dev/null \
			| sed "s/^.*[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\} \(.*\)$/\1/" >> $EXTRASLIST
		#
		# Clean up EXTRASLIST to be passed to base rsync restore
		# as exclude list
		#
		EXTRASLISTLENGTH=$(wc -l $EXTRASLIST|sed 's/^[[:space:]]*\([0-9]*\).*$/\1/')
		cat $EXTRASLIST | sed "1,2d;$(expr $EXTRASLISTLENGTH - 1),${EXTRASLISTLENGTH}d" >> $EXTRASLISTNEW
		rm -f $EXTRASLIST
	fi

	#
	# Do the base restore
	#
	log 2 "doing the base sync (rsync $RSYNC_PARAMS_BASERESTORE $OBNOVAPATH/data/$GROUPNAME/base/$PARTITION/ ${MOUNTPOINT}/)"
	rsync $RSYNC_PARAMS_BASERESTORE $OBNOVAPATH/data/$GROUPNAME/base/$PARTITION/ ${MOUNTPOINT}/ #2>/dev/null>&1
	if [ $? -eq 0 ]; then
		log 3 "base sync OK"
		echo -e $TNS"Obnova diskoveho oddilu $PARTITION byla provedena uspesne."$TNE
		sleep 5
	else
		log 1 "error return code in base sync"
		exit 1
	fi

	#
	# ...and synchronize extras
	#
	if [ "$DATAEXTRASFILESEXISTS" != "false" ]; then log 3 "doing extras sync"
		rsync $RSYNC_PARAMS_EXTRASRESTORE $OBNOVAPATH/data/$GROUPNAME/extras/$MAC/$PARTITION/ ${MOUNTPOINT}/ #2>/dev/null>&1
		if [ $? -eq 0 ]; then
			log 3 "extras sync OK"
			echo -e $TNS"Individualni obnova diskoveho oddilu $PARTITION byla provedena uspesne."$TNE
		else
			log 1 "error return code in extras sync"
			exit 1
		fi
	fi
	rm -f $EXTRASLISTNEW
	#
	# Put selected items into registry 
	#
	COMPNAME=`getcompname`
	REGSYS=`echo $MOUNTPOINT/[Ww][Ii]*/[Ss][Yy]*/[Cc][Oo]*/[Ss][Yy][Ss]*[Mm]`
	REGSW=`echo $MOUNTPOINT/[Ww][Ii]*/[Ss][Yy]*/[Cc][Oo]*/[Ss][Oo][Ff]*[Ee]`
	echo "Software register file: ${REGSYS}"
	echo "System register file: ${REGSW}"
	# Depending on Windows version:
	if [ -f "$REGSW" ] && [ -f "$REGSYS" ]; then
		# Let's suppose it is WinXP or Vista
		#
		# Pro Sanako na b208
		#
		LABNAME=$(echo $COMPNAME|cut -d"-" -f1)
		if [ "$LABNAME" = "b208" ]; then
			COMPID=$(echo $COMPNAME|cut -d"-" -f2)
			SANAKOSTRING1="ed Sanako\Shared Components\NetCommPlatform\Client\ClientId\n$COMPID\nq\ny\n"
			echo -e $SANAKOSTRING1 | chntpw -e $REGSW
			SANAKOSTRING2="ed Sanako\Shared Components\Common\ToLabNumber\n$COMPID\nq\ny\n"
			echo -e $SANAKOSTRING2 | chntpw -e $REGSW
			SANAKOSTRING3="ed Sanako\Lab\Lab300\Duo\Common\ToLabNumber\n$COMPID\nq\ny\n"
			echo -e $SANAKOSTRING3 | chntpw -e $REGSW
		fi
		#
		# Set NETBIOS computer name
		#
		STRING=$STRING"ed \ControlSet001\Services\Tcpip\Parameters\NV Hostname\n$COMPNAME\ned \ControlSet001\Control\ComputerName\ComputerName\ComputerName\n$COMPNAME\nq\ny\n"
		echo -e $STRING | chntpw -e $REGSYS
		#
	fi
	sleep 4
	umount $MOUNTPOINT
done

