#!/bin/sh
#
# Copyright © 2006 Martin F. Krafft <madduck@debian.org>
# based on the scripts in the initramfs-tools package.
# released under the terms of the Artistic Licence.
#
# $Id: hook 290 2006-12-19 08:18:50Z madduck $
#

PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case ${1:-} in
  prereqs)
    prereqs
    exit 0
    ;;
esac

plog ()
{
	if [ -n "$debug" ]; then
		echo $* >&2
	fi
}

[ -r /usr/share/initramfs-tools/hook-functions ] || exit 0
. /usr/share/initramfs-tools/hook-functions

export PATH=$PWD/bin/:$PATH

# Copy commands
for i in ${commands}; do
  plog "Adding /bin/$i"
  copy_exec `which $i` /bin
done

# Copy supercommands
for i in ${scommands}; do
  plog "Addind /sbin/$i"
  copy_exec `which $i` /sbin
done

# Add modules
for i in ${modules}; do
  plog "Adding module $i"
  manual_add_modules ${i}
done

# Copy all needed files to right places
# Create directories if they do not exists
for i in ${copyfiles}; do
  f=`echo $i | cut -d ':' -f 1`
  t=`echo $i | cut -d ':' -f 2`
  plog "Copying $f to $t"
  mkdir -p `dirname "${DESTDIR}/${t}"`
  rm -f "${DESTDIR}/${t}"
  cp "${f}" "${DESTDIR}/${t}"
done

