#!/bin/sh

set -e

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

export LANG=cs_CZ.utf8
export COLUMNS=160

. /scripts/functions
. /etc/common-functions

log_begin_msg "Obnova-ng starting..."

ldconfig
ln -sf /tmp/etc/obnova-joined.conf /etc/obnova.conf
mkdir -p /dev/pts /tmp /sys /sys/fs/fuse/connections
mount -a -n
mkdir -p /var/run/sshd
chown root.root /var/run/sshd
chmod 600 /var/run/sshd

reset
logolite

while ! [ -c /dev/tty3  ] ; do
  # Berlicka - 2x se mountuje /dev
  if [ $(mount |grep /dev | wc -l) -gt 1 ]; then
    umount /dev
  fi
  sleep 1
done
sleep 2

/bin/setupcon
logo

/bin/openvt -c 3 -f /bin/bash
/bin/openvt -c 4 -f /bin/top
(sleep 10; /bin/openvt -c 5 -f /bin/iftop) &
(sleep 10; chvt 2; reset) &
(if [ -f /etc/ssh/sshd_config ]; then /bin/sshd ; fi)

if /bin/openvt -w -c 2 -f /bin/obnovang-stage2; then
  log_begin_msg "Obnova ended."
  sleep 3600
else
  log_begin_msg "Obnova error!"
  sleep 3600
fi

sleep 3600

log_end_msg

