#!/bin/sh

#set -e

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

export LANG=cs_CZ.utf8
export COLUMNS=80

. /scripts/functions
. /etc/common-functions

log_begin_msg "Obnova-ng starting..."

ldconfig
ln -sf /tmp/etc/obnova-joined.conf /etc/obnova.conf
mkdir -p /dev/pts /tmp /sys /sys/
mount -a -n
mkdir -p /var/run/sshd
chown root.root /var/run/sshd
chmod 600 /var/run/sshd

reset
logolite

while ! [ -c /dev/tty3  ] ; do
  # Berlicka - 2x se mountuje /dev
  if [ $(mount |grep /dev | wc -l) -gt 1 ]; then
    umount /dev
  fi
  sleep 1
done
sleep 2

/bin/setupcon
/bin/openvt -c 2 /bin/setupcon
logo

echo "*.* @@syslog" >>/etc/rsyslog.conf

/bin/openvt -c 3 -s -f /bin/sh
/bin/openvt -c 4 -s -f /bin/top
(sleep 10; /bin/openvt -c 5 -f /bin/iftop ) &

if /bin/openvt -w -c 2 -s -f /bin/obnovang-stage2; then
  log_begin_msg "Obnova ended."
  sleep 600
  halt
else
  log_begin_msg "Obnova error!"
  halt
fi

log_end_msg

