#!/bin/sh

if [ -z "$2" ]; then
  echo "Need 2 parameters!"
  echo "$0 [sender|receiver] device"
  echo "Example: $0 sender /dev/sda"
  exit 1
fi

case "$1" in

"sender")
  chvt 2
  reset
  echo "Starting udpcast sender. {compression=$compression}"
  udp-sender --min-wait 5 --max-wait 30 --min-receivers 1 --pipe 'cpipe' --nokbd --ttl 1 </dev/$2
  ;;

"receiver")
  chvt 2
  reset
  echo "Starting udpcast receiver.{compression=$compression"
  udp-receiver --stat-period 1 --print-uncompressed-position 1 --pipe 'upipe' --nokbd --ttl 1 >/dev/$2
  ;;
esac
