#!/bin/sh

if [ -z "$2" ]; then
  echo "Need 2 parameters!"
  echo "$0 [sender|receiver] device"
  echo "Example: $0 sender /dev/sda"
  exit 1
fi

case "$1" in

"sender")
  chvt 2
  reset
  echo "Starting udpcast sender."
  udp-sender --stream --min-receivers 1 --pipe 'cpipe' --start-timeout 1200 --nokbd --ttl 2 </dev/$2
  ;;

"receiver")
  chvt 2
  reset
  echo "Starting udpcast receiver."
  udp-receiver --pipe 'upipe' --nokbd --ttl 2 >/dev/$2
  ;;
esac
