#!/bin/sh

if [ -z "$2" ]; then
  echo "Need 2 parameters!"
  echo "$0 [sender|receiver] device"
  echo "Example: $0 sender /dev/sda"
  exit 1
fi

case "$1" in

"sender")
  chvt 2
  reset
  echo "Starting udpcast sender. Pres ENTER when ready."
  udp-sender --pipe 'cpipe' </dev/$2 --ttl 2 2>/obnova-err.log 2>&1
  ;;

"receiver")
  chvt 2
  reset
  echo "Starting udpcast receiver. Pres ENTER when ready."
  udp-receiver --pipe 'upipe' >/dev/$2  2>/obnova-err.log 2>&1
  ;;
esac
