#!/bin/sh

set -e

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /scripts/functions

log_begin_msg "Obnova-ng starting..."

ln -sf /tmp/etc/obnova-joined.conf /etc/obnova.conf

/bin/openvt -c 4 -f /bin/sh

export LANG=cs_CZ.utf8
if /bin/openvt -w -c 2 -f -s /bin/obnovang-stage2; then
  log_begin_msg "Obnova ended."
  sleep 3600
else
  log_begin_msg "Obnova error!"
  sleep 3600
fi

sleep 3600

log_end_msg
