#!/bin/sh

if [ -z "$1" ]; then
  echo "Need 2 parameters!"
  echo "$0 [sender|receiver] device"
  echo "Example: $0 sender /dev/sda"
  exit 1
fi

case "$1" in

"sender")
  echo "Starting udpcast sender"
  udp-sender --pipe lzop --full-duplex --file /dev/sda --ttl 1 
  ;;

"receiver")
  echo "Starting udpcast receiver"
  udp-receiver --pipe 'lzop -d' --file /dev/sda
  ;;
esac
