#!/bin/sh

set -e

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

export LANG=cs_CZ.utf8

. /scripts/functions

log_begin_msg "Obnova-ng starting..."

ldconfig
ln -sf /tmp/etc/obnova-joined.conf /etc/obnova.conf

reset
echo -e "\033[44;37;1m                                                                               "
echo -e "                  SYSTEM OBNOVY SKUPIN POCITACOVYCH STANIC                     "
echo -e "                   (c)199X Pavel Behal, pavel@behal.cz                         "
echo -e "                   (c)2003,2004 Lukas Kubin, lukas.kubin@gmail.com             "
echo -e "                   (c)2005,2006,2007,2008 Lukas Macura, macura@opf.slu.cz      "
echo -e "                   (c)2008,... Tomas Kralik, runyar@gmail.com                     "
echo -e "                   (c)2008 Jakub Jezisek, Pavel Baco (annoying testers)        "
echo -e "                         Slezska univerzita v Opave                            "
echo -e "                                                                               \033[0m"

/bin/openvt -c 3 -f /bin/bash
/bin/openvt -c 4 -f /bin/top
(sleep 10; /bin/openvt -c 5 -f /bin/iftop) &
(sleep 10; chvt 2) &

if /bin/openvt -w -c 2 -f /bin/obnovang-stage2; then
  log_begin_msg "Obnova ended."
  sleep 3600
else
  log_begin_msg "Obnova error!"
  sleep 3600
fi

sleep 3600

log_end_msg
