#!/bin/sh

if [ -z "$1" ]; then
  echo "Need 2 parameters!"
  echo "$0 [sender|receiver] device"
  echo "Example: $0 sender /dev/sda"
  exit 1
fi

case "$1"in
"sender")
  echo "Starting udpcast sender"
  ;;
"receiver")
  echo "Starting udpcast receiver"
  ;;
esac

