#!/bin/sh

if [ -z "$1" ]; then
  echo "Need 2 parameters!"
  echo "$0 [sender|receiver] device"
  echo "Example: $0 sender /dev/sda"
  exit 1
fi

case "$1" in

"sender")
  echo "Starting udpcast sender"
  (sleep 10; openvt -c 1 -f ddprogress) &
  udp-sender --pipe 'cpipe' --full-duplex --file /dev/sda --ttl 2 --log /dev/tty2
  ;;

"receiver")
  echo "Starting udpcast receiver"
  (sleep 10; openvt -c 1 -f ddprogress) &
  udp-receiver --pipe 'upipe' --file /dev/sda --log /dev/tty2
  ;;
esac
